version: "3"

services:

  webserver:
    image: nginx:alpine
    container_name: idp-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 8081
    environment:
      - VIRTUAL_HOST=idp.grocelivery.eu
      - SHELL=/bin/ash
    depends_on:
      - php

  php:
    container_name: idp-php
    build: .docker/php
    volumes:
      - .:/application
    links:
      - database

  database:
    container_name: idp-database
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=zsz1234
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306

networks:
  default:
    external:
      name: nginx_proxy
