version: "3"

services:

  webserver:
    image: nginx:alpine
    container_name: idp-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 8081
    environment:
      - SHELL=/bin/ash
    depends_on:
      - php-fpm

  php-fpm:
    container_name: idp-php-fpm
    build: .docker/php
    volumes:
      - .:/application
    links:
      - database

  database:
    container_name: idp-database
    image: mysql:5.6
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

networks:
  default:
    external:
      name: nginx_proxy